# Generated by Django 4.0.1 on 2022-06-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ImageField(upload_to='YouTube.IM/%Y/%m')),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
