# Generated by Django 4.0.1 on 2022-06-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube1', '0002_remove_home_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='video',
            field=models.ImageField(default=1, upload_to='YouTube.IM/%Y/%m'),
            preserve_default=False,
        ),
    ]
