# Generated by Django 4.0.1 on 2022-06-02 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube1', '0003_home_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Video',
        ),
    ]
