# Generated by Django 4.0.1 on 2022-06-02 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youtube1', '0005_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
