# Generated by Django 4.0.1 on 2022-06-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube1', '0007_alter_video_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
